config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :show]
  root 'recipes#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = RecipeService.new.recipes
  end

  def show
    @recipe = RecipeService.new.recipe(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleySpoon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  'https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li class="<%= "#{ 'active' if params[:controller] == 'recipes' && params[:action] == 'index'}"%>"><%= link_to 'All Recipes', recipes_path %></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid text-center">
  <%= yield %>
  </div>
  </body>
</html>

app/views/recipes/index.html.erb
<% if @recipes.present? %>
  <h1>All Recipes</h1>
  <% @recipes.each do |recipe| %>
    <div class="row col-md-offset-2">
      <div class="col-md-2">
        <img src="<%= recipe.photo.url(w: 140) %>" alt="Recipe Image">
      </div>
      <div class="col-md-6">
        <div class="row">
          <h4 class="pull-left"><%= recipe.title %></h4>
        </div>
        <div class="row">
          <%= link_to 'Details', recipe_path(recipe.id), class: 'btn btn-primary pull-left' %>
        </div>
      </div>
      <br>
    </div>
    <br/>
  <% end %>
<% else %>
  <h1> No data found for recipes</h1>
<% end %>

app/views/recipes/show.html.erb
<% if @recipe %>
  <div class="container">
    <div class="row">
      <div class="col-md-5">
        <div class="project-info-box mt-0">
          <h5><%= @recipe.title %></h5>
          <p class="mb-0"><%= @recipe.description %></p>
        </div>

        <div class="project-info-box">
          <p><b>Tags:</b>  <%= @recipe.try(:tags).present? ? @recipe.tags.map{|a| a.name.titleize}.try(:join, ',') : '' %></p>
          <p><b>Chef Name:</b> <%= @recipe.chef.try(:name) || '' %></p>
        </div>

      </div>

      <div class="col-md-7">
        <img src="<%= @recipe.photo.url(w: 240) %>" alt="recipe-image" class="rounded">
      </div>
    </div>
  </div>
  <% else %>
  <h1>Recipe Not found</h1>
<% end %>